AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  youtube-line-notification-app

  Sample SAM Template for youtube-line-notification-app

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  LineNotificationFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: line-notification/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Environment:
        Variables:
          API_KEY: ## 自分のAPIキーを入力（暫定対応）
          LineBotChannelSecret: ## LINEのチャネルシークレット（暫定対応）
          LineBotChannelToken:  ## LINEの（暫定対応）
      Events:
        ScheduledEventBridgeRule:
          Type: Schedule
          Properties:
            Schedule: cron(30 8 * * ? *)
            Enabled: true
            Name: ScheduledInvoke
            Description: Rule that Invoke at 17:30 pm(JST)

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: !Sub ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName: !Ref ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'